### ISSUE TITLE
Module name not set properly in `go.mod`

### ISSUE THREAD

**Issue by bstncartwright** [snyk/leaky-vessels-static-detector#10]
In the `go.mod` file the module is currently set as `static-detector`. This works if we want to  clone the module and run it that way, but if we want to run the module with `go run github.com/synk/leaky-vessels-static-detector@latest` (to not require cloning and such, just running it).

To fix this all we would need to do is update the `go.mod` file to have the module be `github.com/synk/leaky-vessels-static-detector`.

**Comment by supriza** [comment]
Hi @bstncartwright, you're of course right - the project will not work as a Go module as it was intended to run as a cli tool. Unfortunately, that rather small change will require us to amend quite a lot of external communications. As a workaround I suggest you fork the repo and run `go mod edit -replace static-detector=[YOUR URL]` and also change the scope of any private functions you'd like to export. Hope this helps :)
